### ISSUE TITLE
Management of global objects

### ISSUE THREAD

**Issue by maximkrouk** [V8tr/ModernMVVM#2]
Do you have any best practices (of user management, for example), that can fit into this architecture?

**Comment by V8tr** [comment]
I've intentionally avoided this topic for two reasons:

1. It does not relate to the MVVM architecture directly since MVVM can sit on top of any model and infrastructure architecture.
2. I don't have an exact answer yet 🙂. I am currently working on this topic and hopefully will be able to write about it in the next couple of weeks.
